# Generated by Django 5.1.4 on 2025-01-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Esta imagen se mostrará tanto en el listado como en el detalle del post', null=True, upload_to='posts/%Y/%m/', verbose_name='Imagen destacada'),
        ),
    ]
